### ISSUE TITLE
Save the new processed data as .csv

### ISSUE THREAD

**Issue by jamesh14** [DSCI-310-2024/DSCI310-group10-project#29]
- save the transformed raw data as .csv
- create a folder for processed data

**Comment by cass12345** [comment]
data preprocessing should be an individual part of our report, isn't it? Or do u just want to save the cleaned data as a backup?

**Comment by jamesh14** [comment]
> data preprocessing should be an individual part of our report, isn't it? Or do u just want to save the cleaned data as a backup?

im just saving it as backup for now, we can generate it using the script
